// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Gallery struct {
	ID        int64              `json:"id"`
	Image     pgtype.Text        `json:"image"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Inventory struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Image     pgtype.Text        `json:"image"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             int64              `json:"id"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	Role           string             `json:"role"`
	Suspended      bool               `json:"suspended"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
